# Name-Aniket Bhavar,Roll No-321
   

In [71]:
# Libraries for this section 
import numpy as np
import pandas as p

# Basic vector operations

In [2]:
x = np.array([[1],
              [2],
              [3]])

In [3]:
x.shape # (3 dimensions, 1 element on each)

(3, 1)

In [4]:
print(f'A 3-dimensional vector:\n{x}')

A 3-dimensional vector:
[[1]
 [2]
 [3]]


In [5]:
x = y = np.array([[1],
                  [2],
                  [3]])

In [6]:
x + y

array([[2],
       [4],
       [6]])

In [7]:
np.add(x,y)

array([[2],
       [4],
       [6]])

In [8]:
alpha = 2
x = np.array([[1],
             [2],
             [3]])

In [9]:
alpha * x

array([[2],
       [4],
       [6]])

In [10]:
a, b = 2, 3
x , y = np.array([[2],[3]]), np.array([[4], [5]])

In [11]:
a*x + b*y

array([[16],
       [21]])

# Vector-vector multiplication: dot product 

In [12]:
x, y = np.array([[-2],[2]]), np.array([[4],[-3]])

In [13]:
x.T @ y

array([[-14]])

# Vector space, span, and subspace

In [14]:
x = np.array([[3],[4]])

np.linalg.norm(x, 2)

5.0

In [15]:
x = np.array([[3],[-4]])

np.linalg.norm(x, 1)

7.0

In [16]:
x = np.array([[3],[-4]])

np.linalg.norm(x, np.inf)

4.0

# Vector inner product, length, and distance.

In [17]:
x, y = np.array([[-2],[2]]), np.array([[4],[-3]])
x.T @ y 

array([[-14]])

In [18]:
distance = np.linalg.norm(x-y, 2)
print(f'L_2 distance : {distance}')

L_2 distance : 7.810249675906654


# Vector angles and orthogonality

In [19]:
x, y = np.array([[1], [2]]), np.array([[5], [7]])

# here we translate the cos(theta) definition
cos_theta = (x.T @ y) / (np.linalg.norm(x,2) * np.linalg.norm(y,2))
print(f'cos of the angle = {np.round(cos_theta, 3)}')

cos of the angle = [[0.988]]


In [20]:
cos_inverse = np.arccos(cos_theta)
print(f'angle in radiants = {np.round(cos_inverse, 3)}')

angle in radiants = [[0.157]]


In [21]:
degrees = cos_inverse * ((180)/np.pi)
print(f'angle in degrees = {np.round(degrees, 3)}')

angle in degrees = [[8.973]]


In [22]:
x = np.array([[2], [0]])
y = np.array([[0], [2]])

cos_theta = (x.T @ y) / (np.linalg.norm(x,2) * np.linalg.norm(y,2))
print(f'cos of the angle = {np.round(cos_theta, 3)}')

cos of the angle = [[0.]]


In [23]:
cos_inverse = np.arccos(cos_theta)
degrees = cos_inverse * ((180)/np.pi)
print(f'angle in radiants = {np.round(cos_inverse, 3)}\nangle in degrees ={np.round(degrees, 3)} ')


angle in radiants = [[1.571]]
angle in degrees =[[90.]] 


# Basic Matrices Operation

In [24]:
A = np.array([[0,2],  # 1st row
              [1,4]]) # 2nd row

print(f'a 2x2 Matrix:\n{A}')

a 2x2 Matrix:
[[0 2]
 [1 4]]


In [25]:
A = np.array([[0,2],
              [1,4]])
B = np.array([[3,1],
              [-3,2]])

In [26]:
A + B

array([[ 3,  3],
       [-2,  6]])

In [27]:
np.add(A, B)

array([[ 3,  3],
       [-2,  6]])

In [28]:
alpha = 2
A = np.array([[1,2],
              [3,4]])

In [29]:
alpha * A

array([[2, 4],
       [6, 8]])

In [30]:
np.multiply(alpha, A)

array([[2, 4],
       [6, 8]])

In [31]:
# dot Product

In [32]:
A = np.array([[0,2],
              [1,4]])
x = np.array([[1],
              [2]])

In [33]:
A @ x

array([[4],
       [9]])

In [34]:
np.dot(A, x)

array([[4],
       [9]])

In [35]:
A = np.array([[0,2],
              [1,4]])
B = np.array([[1,3],
              [2,1]])

In [36]:
A @ B

array([[4, 2],
       [9, 7]])

In [37]:
np.dot(A, B)

array([[4, 2],
       [9, 7]])

In [38]:
# matrix identity
# matrix inverse

In [39]:
A = np.array([[1, 2, 1],
              [4, 4, 5],
              [6, 7, 7]])

In [40]:
A_i = np.linalg.inv(A)
print(f'A inverse:\n{A_i}')

A inverse:
[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]


In [41]:
I = np.round(A_i @ A)
print(f'A_i times A resulsts in I_3:\n{I}')

A_i times A resulsts in I_3:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]


In [42]:
# matrix transpose

In [43]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [44]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [45]:
# rectanguler,squre,Diagonal,upper lower triangular matrix,symetric,identity,scaler,echelon,


#  Matrices as systems of linear equations 

In [46]:
A = np.array([[1, 3, 5],
              [2, 2, -1],
              [1, 3, 2]])
y = np.array([[-1],
              [1],
              [2]])

In [47]:
np.linalg.solve(A, y)

array([[-2.],
       [ 2.],
       [-1.]])

In [48]:
from sympy import Matrix

In [49]:
 A = Matrix([[1, 0, 1],
            [0, 1, 1]])

In [50]:
B = Matrix([[1, 2, 3, -1],
            [2, -1, -4, 8],
            [-1, 1, 3, -5],
            [-1, 2, 5, -6],
            [-1, -2, -3, 1]])

In [51]:
A_rref, A_pivots = A.rref()


In [52]:
print('Reduced row echelon form of A:')

Reduced row echelon form of A:


In [53]:
print(f'Column pivots of A: {A_pivots}')

Column pivots of A: (0, 1)


In [54]:
B_rref, B_pivots = B.rref()

In [55]:
print('Reduced row echelon form of B:')

Reduced row echelon form of B:


In [56]:
x = np.array([[-1],
              [0],
              [1]])

y = np.array([[-3],
              [0],
              [2]])

T = np.array([[-1,0,0],
              [0,-1,0],
              [0,0,-1]])

In [57]:
left_side_1 = T @ (x+y)
right_side_1 = (T @ x) + (T @ y)
print(f"Left side of the equation:\n{left_side_1}")
print(f"Right side of the equation:\n{right_side_1}")

Left side of the equation:
[[ 4]
 [ 0]
 [-3]]
Right side of the equation:
[[ 4]
 [ 0]
 [-3]]


In [58]:
alpha = 2
left_side_2 = T @ (alpha * x)
right_side_2 = alpha * (T @ x)
print(f"Left side of the equation:\n{left_side_2}")
print(f"Right side of the equation:\n{right_side_2}")

Left side of the equation:
[[ 2]
 [ 0]
 [-2]]
Right side of the equation:
[[ 2]
 [ 0]
 [-2]]


# Reversal matrix 

In [59]:
x = np.array([[-1],
              [0],
              [1]])

y = np.array([[-3],
              [0],
              [2]])

T = np.array([[0,0,1],
              [0,1,0],
              [1,0,0]])

In [60]:
x_reversal = T @ x
y_reversal = T @ y
left_side_1 = T @ (x+y)
right_side_1 = (T @ x) + (T @ y)
print(f"x before reversal:\n{x}\nx after reversal \n{x_reversal}")
print(f"y before reversal:\n{y}\ny after reversal \n{y_reversal}")
print(f"Left side of the equation (add reversed vectors):\n{left_side_1}")
print(f"Right side of the equation (add reversed vectors):\n{right_side_1}")

x before reversal:
[[-1]
 [ 0]
 [ 1]]
x after reversal 
[[ 1]
 [ 0]
 [-1]]
y before reversal:
[[-3]
 [ 0]
 [ 2]]
y after reversal 
[[ 2]
 [ 0]
 [-3]]
Left side of the equation (add reversed vectors):
[[ 3]
 [ 0]
 [-4]]
Right side of the equation (add reversed vectors):
[[ 3]
 [ 0]
 [-4]]


# Determinant 

In [61]:
A = np.array([[4, 0],
              [0, 3]])

x = np.array([1,1])

In [62]:
A @ x.T

array([4, 3])

In [63]:
T = np.array([[2, -2],
              [2,  2]])

# Inverse of T
T_i = np.linalg.inv(T)

# x, y vectors
A = np.array([[1, 0],
              [0,1]])

print(f"x, y vectors in x', y' coordinates:\n{T_i @ A}")

x, y vectors in x', y' coordinates:
[[ 0.25  0.25]
 [-0.25  0.25]]


In [64]:
# vector to map
a = np.array([[-3],[-1]])
print(f'Vector a=[1,3] in x\' and y\' basis:\n{T_i@a}')

Vector a=[1,3] in x' and y' basis:
[[-1. ]
 [ 0.5]]


# Eigenvectors, Eigenvalues and Eigenspaces 

In [65]:
A = np.array([[4, 2],
              [1, 3]])

values, vectors = np.linalg.eig(A)

In [66]:
print(f'Eigenvalues of A:\n{values}\n')
print(f'Eigenvectors of A:\n{np.round(vectors,3)}')

Eigenvalues of A:
[5. 2.]

Eigenvectors of A:
[[ 0.894 -0.707]
 [ 0.447  0.707]]


In [67]:
B = np.array([[0, -1],
              [1, 0]])

values, vectors = np.linalg.eig(B)

In [68]:
print(f'B Eigenvalues:\n{values}\n')
print(f'B Eigenvectors:\n{vectors}\n')

B Eigenvalues:
[0.+1.j 0.-1.j]

B Eigenvectors:
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]



# Eigendecomposition 

In [69]:
A = np.array([[5,  3, 0],
              [2,  6, 0], 
              [4,  -2, 2]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print(f'B Eigenvalues:\n{eigenvalues}\n')
print(f'B Eigenvectors:\n{eigenvectors}\n')

B Eigenvalues:
[2. 8. 3.]

B Eigenvectors:
[[ 0.          0.6882472   0.18291323]
 [ 0.          0.6882472  -0.12194215]
 [ 1.          0.22941573  0.97553722]]



In [70]:
X = eigenvectors 
I = np.identity(3)
L = I * eigenvalues
print(f'Left-side of the equation AX:\n{A @ X}\n')
print(f'Right-side of the equation XL:\n{X @ L}\n')

Left-side of the equation AX:
[[ 0.          5.50597761  0.54873968]
 [ 0.          5.50597761 -0.36582646]
 [ 2.          1.83532587  2.92661165]]

Right-side of the equation XL:
[[ 0.          5.50597761  0.54873968]
 [ 0.          5.50597761 -0.36582646]
 [ 2.          1.83532587  2.92661165]]

