### Scalar

A Scalar is a quantity which is described by a numerical value. It is used to represent values such as:
A number like 50
Mass of sun in kilograms 
Length of the great wall of china in kilometres


In [ ]:
# Define scalars
number_of_units = 50
mass_of_sun = 1.989e30
length_great_wall_of_china = 21196
print(number_of_units)
print(mass_of_sun)
print(length_great_wall_of_china)


50
1.989e+30
21196


### Vector
A vector is an ordered collection of scalars. It can be represented in two forms:

Column vector: Contains n rows and 1 column
Row vector: Contains 1 row and n columns
The number of scalars in a vector is called its dimension or order. 

Example: A column vector 'u' of dimension 2 is illustrated below:



Example: A row vector 'v' of dimension 3 is illustrated below:



Row and column vectors can be created using the library NumPy as follows: 

In [ ]:
# importing required library (numpy as np)
import numpy as np
# creating a column vector with 2 rows and 1 column using np.array() function
col_vec = np.array([[4],[3]])
print ("A column vector\n",col_vec)
# printing the shape of the vector
print("Shape of vector=",col_vec.shape)


A column vector
 [[4]
 [3]]
Shape of vector= (2, 1)


In [ ]:
# importing required library (numpy as np)
import numpy as np
# creating a row vector with 1 row and 3 columns using np.array() function
row_vec = np.array([[4,-1,2]])
print("A row vector\n",row_vec)
# printing the shape of the vector
print("Shape of vector=",row_vec.shape)


A row vector
 [[ 4 -1  2]]
Shape of vector= (1, 3)


Zero vector (z) is a vector in which each element is zero.

One vector (o) is a vector in which each element is one.

In [ ]:
# importing required library (numpy as np)
import numpy as np
#Illustrating a Zero row vector of dimension 3 using np.array() function
zero_vector_1=np.array([0,0,0])
print(zero_vector_1)
#Illustrating a Zero row vector of dimension 3 using np.zeros() function
zero_vector_2=np.zeros(3)
print(zero_vector_2)
#Illustrating a Zero column vector of dimension 3 using np.zeros() and reshape() function
zero_vector_3=np.zeros(3).reshape(3,-1)
print(zero_vector_3)


[0 0 0]
[0. 0. 0.]
[[0.]
 [0.]
 [0.]]


In [ ]:
# importing required library (numpy as np)
import numpy as np
#Illustrating a One vector of dimension 3 using np.array() function
one_vector_1=np.array([1,1,1])
print(one_vector_1)
#Illustrating a One vector of dimension 3 using np.ones() function
one_vector_2=np.ones(3)
print(one_vector_2)
#Illustrating a column vector of ones of dimension 3 using np.ones() and reshape() function 
one_vector_3=np.ones(3).reshape(3,-1)
print(one_vector_3)


[1 1 1]
[1. 1. 1.]
[[1.]
 [1.]
 [1.]]


In [ ]:
## Indexing

# importing required libraries (numpy as np)
import numpy as np
vector=np.array([[4],[-1],[2]])
print("The vector\n",vector)
#Addressing a value of vector by index
print("\nElement at position 1=",vector[1])


The vector
 [[ 4]
 [-1]
 [ 2]]

Element at position 1= [-1]


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
#Create a vector
vector=np.array([3,3,3])
#Magnitude of vector can be found using function np.linalg.norm() function
print("\nMagnitude of the vector = ",np.linalg.norm(vector))



Magnitude of the vector =  5.196152422706632


### Matrix
A matrix is defined as a rectangular array of numbers. It consists of rows and columns. 

The number of rows (m) and columns (n) is defined as the dimension or order of the matrix and is represented as (m, n). A matrix is called a square matrix if the number of rows(m) is equal to the number of columns(n).

Using the library NumPy, you can create matrices of different orders as shown below:

In [ ]:
# importing required libraries (numpy as np)
import numpy as np
# Creating matrices of various dimension using np.array() function
matrix_2x2 = np.array([[1, 2], 
                       [3, 4]])
matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [8, 9, 10]])
print("2x2 Matrix\n",matrix_2x2,"\nshape of matrix -> ",matrix_2x2.shape)
print("\n3x3 Matrix\n",matrix_3x3,"\nshape of matrix -> ",matrix_3x3.shape)


2x2 Matrix
 [[1 2]
 [3 4]] 
shape of matrix ->  (2, 2)

3x3 Matrix
 [[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]] 
shape of matrix ->  (3, 3)


In [ ]:
#Accessing elements of a matrix
# importing required libraries (numpy as np)
import numpy as np
# Creating a 3x2 Matrix "A"
A = np.array([[2,-2],[3,1],[1,4]])
# Recall that, indexing starts from 0. Elements of matrix A can be accessed using row-id and column-id as shown below:

#selecting an element at row index 2 and column index 1
print("Element of matrix A at index position [2,1] is", A[2,1])


Element of matrix A at index position [2,1] is 4


## Transpose of a matrix
Transpose of a matrix is obtained by interchanging its rows and columns.
Note: The matrix A has 3 rows and 2 columns, and its Transpose has 2 rows and 3 columns.

NumPy library has a function transpose() which is used to obtain the transpose of a given matrix. 

An example is illustrated below:

In [ ]:
# importing required libraries (numpy as np)
import numpy as np
# Creating a 3x2 Matrix "A"
A = np.array([[2,-2],[3,1],[1,4]])
print("Matrix A:\n",A)
# Finding transpose of a matrix using the function transpose()
print("Matrix A Transpose: \n",np.transpose(A))


Matrix A:
 [[ 2 -2]
 [ 3  1]
 [ 1  4]]
Matrix A Transpose: 
 [[ 2  3  1]
 [-2  1  4]]


Types of Matrices
Matrices can be categorized on the basis of the value of their elements, position of elements,  number of rows and columns, etc. as follows:
Diagonal matrix

Identity matrix

Symmetric matrix

Triangular matrix


Diagonal Matrix
A Square Matrix (D) is called a Diagonal Matrix, if D has zeros outside the main diagonal or principal diagonal. The Main diagonal or the principal diagonal are the elements on the diagonal that runs from the top left to bottom right. 

Example: The matrix 'A' shown below illustrates a (3, 3) Diagonal matrix.

In [ ]:
# importing required libraries (numpy as np)
import numpy as np
# Creating a diagonal matrix with diagonal elements as (1,3,2)
diagonal_matrix = np.diag((1,3,2))
print(diagonal_matrix)
# Creating a diagonal matrix with a range of values
matrix_range= np.diag(np.arange(1,6,2))
print(matrix_range)


[[1 0 0]
 [0 3 0]
 [0 0 2]]
[[1 0 0]
 [0 3 0]
 [0 0 5]]


### Identity Matrix
An identity matrix is a square matrix of dimensions (n, n) having '1' across its main diagonal and '0' everywhere else. It is usually represented as 'In'

Example: The matrix shown below illustrates a (3, 3) Identity matrix.

In [ ]:
# importing required libraries (numpy as np)
import numpy as np
#Creating an Identity matrix of size 2 using np.identity() function
identity_matrix_1 = np.identity(2)
print("Identity_matrix 1\n",identity_matrix_1)
#Creating an Identity matrix of size 3 using np.eye() fucntion
identity_matrix_2 = np.eye(3)
print("\nIdentity_matrix 2\n",identity_matrix_2)


Identity_matrix 1
 [[1. 0.]
 [0. 1.]]

Identity_matrix 2
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Symmetric Matrix
A square matrix A of dimension (n, n) is symmetric, if A = AT i.e.  the matrix A is the same as its transpose.

In [ ]:
# importing required libraries (numpy as np)
import numpy as np
#Creating matrix A
A = np.array([[2,3,1],
            [3,4,-1],
            [1,-1,1]])
print("A:\n" , A)
# Finding the Transpose of the matrix
transposed_matrix = A.transpose()
print("Transpose of A:\n" , transposed_matrix)
#Comparing each element of both matrices (returns a matrix of boolean compared values) and saving it in a variable comparison
comparison = (A == transposed_matrix)
#Checking if all the elements in the matrix comparision is true
equal_arrays = comparison.all()
print(equal_arrays)


A:
 [[ 2  3  1]
 [ 3  4 -1]
 [ 1 -1  1]]
Transpose of A:
 [[ 2  3  1]
 [ 3  4 -1]
 [ 1 -1  1]]
True


### Triangular Matrix
A triangular matrix can be either a lower triangular or an upper triangular matrix.

A lower triangular matrix is a square matrix in which all the elements above the main diagonal are zero.

In [ ]:
# importing required libraries (numpy as np)
import numpy as np
#Creating a lower triangular matrix
lower_triangular_matrix_1 = np.tril([[1,2,3],
                               [4,5,6],
                               [7,8,9]])
print("Lower triangular matrix\n",lower_triangular_matrix_1)


Lower triangular matrix
 [[1 0 0]
 [4 5 0]
 [7 8 9]]


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
#Creating a Upper triangular matrix
upper_triangular_matrix_1 = np.triu([[1,2,3],
                               [4,5,6],
                               [7,8,9]])
print("Upper triangular matrix\n",upper_triangular_matrix_1)


Upper triangular matrix
 [[1 2 3]
 [0 5 6]
 [0 0 9]]


Exercise
Create a square matrix A of order 3. Solve the following:

Convert A to an upper triangular matrix B
 
Convert B to a lower triangular matrix C
 
Find the transpose of matrix C
 
Check whether matrix C is a diagonal matrix
 
Check whether matrix C is symmetric